---
- hosts: localhost
  vars:
    state: present
    s3_bucket: ansiblebucketseptemb2
    key: terraform.tfstate
    region: us-east-1
  tasks:
    - name: Run terraform scripts
      terraform:
        project_path: "./" 
        state: "{{ state }}"
        backend_config:
          bucket: "{{s3_bucket}}"
          key: "{{key}}"
          region: "{{region}}"
